import exceptions

print(exceptions.greet('Timur'))
